spring.application.name=service

server.servlet.context-path=/aterrizar
server.port=8080

springdoc.api-docs.path=/openapi
springdoc.swagger-ui.path=/swagger-ui.html

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=redis

# HTTP CLIENTS
http.client.aviator.base.url=http://localhost:3001/aviator/api/
http.client.experimental.platform.base.url=http://localhost:3001/experimentation/api/
http.client.tax.base.url=http://localhost:3001/tax-service/

# FEATURES
feature.digital.visa.enabled-countries=IN,AU